[package]
name = "mcpg-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
mcpg-domain = { path = "../mcpg-domain" }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
testing = []

[dev-dependencies]
mcpg-mcp = { path = ".", features = ["testing"] }
